config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :tracks
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tracks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  validates :DIno, presence: true, uniqueness:true
  validates :name, presence: true
  validates :age, presence: true
  belongs_to :track
end

app/models/track.rb
class Track < ApplicationRecord
    validates :name, presence: true, uniqueness:true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :age, :DIno, :track_id)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track, only: %i[ show edit update destroy ]

  # GET /tracks or /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1 or /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks or /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to track_url(@track), notice: "Track was successfully created." }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1 or /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to track_url(@track), notice: "Track was successfully updated." }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1 or /tracks/1.json
  def destroy
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url, notice: "Track was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Day1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <%
=begin%>
 <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
<%
=end%>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
    <p style="color: red"> <%= student.errors[:name][0]%></p>
  </div>

<% print student.errors[:name][0]%>
  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
    <p style="color: red"> <%= student.errors[:age][0]%></p>
  </div>

  <div>
    <%= form.label :DIno, style: "display: block" %>
    <%= form.number_field :DIno %>
    <p style="color: red"> <%= student.errors[:DIno][0]%></p>
  </div>

  <div>
    <%= form.label :track_id, style: "display: block" %>
    <%= form.text_field :track_id %>
    <p style="color: red"> <%= student.errors[:track][0]%></p>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= student.age %>
  </p>

  <p>
    <strong>Dino:</strong>
    <%= student.DIno %>
  </p>

  <p>
    <strong>Track:</strong>
    <%= student.track_id %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/tracks/_form.html.erb
<%= form_with(model: track) do |form| %>
  <%
=begin%>
 <% if track.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
<%
=end%>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
    <p style="color: red"> <%= track.errors[:name][0]%></p>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
    <p style="color: red"> <%= track.errors[:description][0]%></p>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<div id="<%= dom_id track %>">
  <p>
    <strong>Name:</strong>
    <%= track.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= track.description %>
  </p>

</div>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Show this track", @track %> |
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tracks</h1>

<div id="tracks">
  <% @tracks.each do |track| %>
    <%= render track %>
    <p>
      <%= link_to "Show this track", track %>
    </p>
  <% end %>
</div>

<%= link_to "New track", new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @track %>

<div>
  <%= link_to "Edit this track", edit_track_path(@track) %> |
  <%= link_to "Back to tracks", tracks_path %>

  <%= button_to "Destroy this track", @track, method: :delete %>
</div>